### ISSUE TITLE
Install capability for RHEL8 ?

### ISSUE THREAD

**Issue by salderma** [mrlesmithjr/ansible-frr#34]
Hi,

RH is distributing frr-7.0.5.el8.rpm with RHEL 8, from the AppStream channel/repo.  Can this role be setup to support installing that with dnf?

Will this role otherwise work for FRR versions > 7.0?

Thanks!

**Comment by elcomtik** [comment]
Another option that I'm considering is to use FRR RPM repository https://rpm.frrouting.org/, which provides the latest stable builds for Centos8. This will limit the possibility to choose the specific version, because only frr-6, frr-7, frr-stable are available.

@salderma I use this role for frr-7.2 on my centos7 and also centos8(without install of package)

I may do PR to add this feature, @mrlesmithjr it is something, which you would accept?

**Comment by salderma** [comment]
The project I was working on ended up taking a different direction away from using this role.  For my part, this issue can be closed as no longer needed, but I'll leave that to someone.

As far as using FRR's repos (or anyone else's, to include EPEL) instead of RHEL8, this would require vetting for software approval for my organization to utilize...it's all part of why we pay for RHEL.

**Comment by elcomtik** [comment]
@mrlesmithjr if there is no one else who needs this, it can be closed. For other people who are able to use FRR repo, my PR https://github.com/mrlesmithjr/ansible-frr/pull/40 should be sufficient.

**Comment by mrlesmithjr** [comment]
Closing this out
